### ISSUE TITLE
Looks like this project is not finished

### ISSUE THREAD

**Issue by java1488** [ignl/happyfacescrud#2]
This is a great project for learning JSF + Spring + Primefaces. Thank you very much. 

Looks like this project is not finished yet, in the formField.xhtml, there is a line "not implemented. formField.xhtml line 248" , the child list doesn't have 'add new' function. 

Do you have any timeline to finish it ? This is great project, please don't leave it incomplete. 

![image](https://user-images.githubusercontent.com/37756766/37870117-e3e7d824-2f9b-11e8-8b7d-2943720df2ad.png)

**Comment by ignl** [comment]
Thank you, I'm glad you liked it. Unfortunately I am not working with JSF anymore right now and have other commitments and project as it is is pretty usable and have a lot of features. If someone could make a pull request I would be glad to merge it. Implementing a missing feature is even better for learning so maybe you are up to the challenge :)

**Comment by java1488** [comment]
sure, I worked on it a little bit. in the accountEdit.xhtml, added:
```

 <p:dialog id="account#{accountBean.objectId}_operationsFormPopupdialog"  
                   widgetVar="account#{accountBean.objectId}_operationsFormPopupdialog" 
                   dynamic="true"                   
                   width="600">
             <hf:formPanel id="formPanel123" label="#{messages['operation.page.panel']}" backingBean="#{operationBean}" columns="1" >
                 <hf:formField  label="#{messages['operation.operationName']}" field="operationName" />            
                 <hf:formField  label="#{messages['operation.operationDate']}" field="operationDate" />
             </hf:formPanel>
        </p:dialog>
```

the dialog is shown, but the input not. looks like we set the 'edit' mode
![image](https://user-images.githubusercontent.com/37756766/37879815-854616ee-304c-11e8-87b0-f9da7f1a2d37.png)

Do you have any idea ? how to set it ?

**Comment by ignl** [comment]
Try to add edit="true" parameter to hf:formField (same as in changePassword.xhtml).
